apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestor
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
        - name: ingestor
          image: {{ .Values.ingestor.image }}
          ports:
            - containerPort: {{ .Values.ingestor.port }}
          env:
            - name: KAFKA_URL
              value: broker:29092

---
apiVersion: v1
kind: Service
metadata:
  name: ingestor
spec:
  selector:
    app: ingestor
  ports:
    - port: {{ .Values.ingestor.port }}
      targetPort: {{ .Values.ingestor.port }}
