FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY api/target/scala-3.6.4/api-assembly-0.1.0-SNAPSHOT.jar /app/api.jar

# include logging config
COPY api/src/main/resources/logback.xml /app/logback.xml
ENV JAVA_OPTS="-Dlogback.configurationFile=/app/logback.xml"

ENTRYPOINT ["java", "-jar", "/app/api.jar"]
