FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY ingestor/target/scala-3.6.4/ingestor-assembly-0.1.0-SNAPSHOT.jar /app/ingestor.jar

# include logging config
COPY ingestor/src/main/resources/logback.xml /app/logback.xml
ENV JAVA_OPTS="-Dlogback.configurationFile=/app/logback.xml"

ENTRYPOINT ["java", "-jar", "/app/ingestor.jar"]
