FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

COPY processor/target/scala-3.6.4/processor-assembly-0.1.0-SNAPSHOT.jar /app/processor.jar

# include logging config
COPY processor/src/main/resources/logback.xml /app/logback.xml
ENV JAVA_OPTS="-Dlogback.configurationFile=/app/logback.xml"

ENTRYPOINT ["java", "-jar", "/app/processor.jar"]
