name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [ 'main', 'development' ]
  pull_request:
    branches: [ 'main', 'development' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      #        TODO: determine how to check formatting for all files at once
      #      - name: Check formatting with bazel
      #        run: ???

      #        TODO: check formatting of bazel files as well

      - name: Build with bazel
        run: bazel build //...

      #      - name: Set up Docker Buildx
      #        uses: docker/setup-buildx-action@v3
      #        if: github.ref == 'refs/heads/main'

      - name: Build ingestor image
        run: |
          bazel run //ingestor:ingestor_docker && \
          docker tag argus-ingestor:latest ${{ secrets.DOCKER_USERNAME }}/argus-ingestor:latest
        if: github.ref == 'refs/heads/main'

      - name: Build processor image
        run: |
          bazel run //processor:processor_docker && \
          docker tag argus-processor:latest ${{ secrets.DOCKER_USERNAME }}/argus-processor:latest
        if: github.ref == 'refs/heads/main'

      - name: Build api image
        run: |
          bazel run //api:api_docker && \
          docker tag argus-api:latest ${{ secrets.DOCKER_USERNAME }}/argus-api:latest
        if: github.ref == 'refs/heads/main'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push ingestor to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/argus-ingestor:latest

      - name: Push processor to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/argus-processor:latest

      - name: Push api to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/argus-api:latest
