name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

#        TODO: determine how to check formatting for all files at once
#      - name: Check formatting with bazel
#        run: ???

#        TODO: check formatting of bazel files as well

      - name: Build with bazel
        run: bazel build //...
