# sbt api/clean api/compile ingestor/clean ingestor/compile processor/clean processor/compile assembly

name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Set up sbt
        uses: sbt/setup-sbt@v1

      - name: Compile and assemble projects
        run: sbt api/clean api/compile ingestor/clean ingestor/compile processor/clean processor/compile assembly

      - name: Check formatting with scalafmt
        run: sbt scalafmtCheck

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push argus-api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: brendonhab/argus-api:latest
          platforms: linux/amd64,linux/arm64

      - name: Build and push argus-ingestor
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ingestor
          push: true
          tags: brendonhab/argus-ingestor:latest
          platforms: linux/amd64,linux/arm64

      
      - name: Build and push argus-processor
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.processor
          push: true
          tags: brendonhab/argus-processor:latest
          platforms: linux/amd64,linux/arm64
